# Generated by Django 3.0.1 on 2020-07-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Class ')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='User Last Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('pincode', models.IntegerField(verbose_name='Pin Code')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Solution Title')),
                ('video', models.FileField(blank=True, null=True, upload_to='class/', verbose_name='Upload Video')),
                ('Class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VidSolutions.Class')),
            ],
        ),
    ]
