# Generated by Django 3.0.1 on 2020-07-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VidSolutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosolutions',
            old_name='Class_section',
            new_name='class_section',
        ),
    ]
