# Generated by Django 3.0.1 on 2020-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VidSolutions', '0002_auto_20200730_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosolutions',
            name='class_section',
            field=models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Class'),
        ),
    ]
